version: '3'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_UID=jekyll
    command: bundle exec jekyll serve --host 0.0.0.0
